package shortlink.elari39.github.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.LocalDateTime;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.data.redis.core.ValueOperations;

import shortlink.elari39.github.config.AppProperties;
import shortlink.elari39.github.dto.CreateLinkRequest;
import shortlink.elari39.github.dto.LinkResponse;
import shortlink.elari39.github.dto.LinkStatsResponse;
import shortlink.elari39.github.entity.AccessLog;
import shortlink.elari39.github.entity.ShortLink;
import shortlink.elari39.github.exception.CodeConflictException;
import shortlink.elari39.github.exception.LinkExpiredException;
import shortlink.elari39.github.exception.LinkNotFoundException;
import shortlink.elari39.github.repository.AccessLogRepository;
import shortlink.elari39.github.repository.ShortLinkRepository;
import shortlink.elari39.github.util.Base62;

/**
 * {@link ShortLinkServiceImpl} 核心逻辑单元测试（Mock 仓储与 Redis）。
 */
@ExtendWith(MockitoExtension.class)
class ShortLinkServiceImplTest {

    @Mock
    private ShortLinkRepository shortLinkRepository;
    @Mock
    private AccessLogRepository accessLogRepository;
    @Mock
    private StringRedisTemplate redis;
    @Mock
    private ClickStatService clickStatService;
    @Mock
    private ValueOperations<String, String> valueOps;

    private ShortLinkServiceImpl service;

    @BeforeEach
    void setUp() {
        // baseUrl / seqStart=100000 / ttl=60 / 短码长度 4~16
        AppProperties properties = new AppProperties("https://shorten.miku831.fun", 100000L, 60L, 4, 16);
        service = new ShortLinkServiceImpl(
                shortLinkRepository, accessLogRepository, redis, clickStatService, properties);
        // 大多数用例会用到 opsForValue，统一宽松桩
        lenient().when(redis.opsForValue()).thenReturn(valueOps);
    }

    @Test
    void createWithAutoGeneratedCode() {
        when(valueOps.setIfAbsent(anyString(), anyString())).thenReturn(true);
        when(valueOps.increment("shortlink:seq")).thenReturn(100000L);
        when(shortLinkRepository.save(any(ShortLink.class))).thenAnswer(inv -> inv.getArgument(0));

        CreateLinkRequest req = new CreateLinkRequest("https://example.com/page", null, null);
        LinkResponse resp = service.createShortLink(req, "https://shorten.miku831.fun");

        assertEquals(Base62.encode(100000L), resp.code());
        assertFalse(resp.custom());
        assertEquals("https://shorten.miku831.fun/" + resp.code(), resp.shortUrl());
    }

    @Test
    void createWithCustomCodeSucceeds() {
        when(shortLinkRepository.existsByCode("mylink")).thenReturn(false);
        when(shortLinkRepository.save(any(ShortLink.class))).thenAnswer(inv -> inv.getArgument(0));

        CreateLinkRequest req = new CreateLinkRequest("https://example.com", "mylink", null);
        LinkResponse resp = service.createShortLink(req, "https://shorten.miku831.fun");

        assertEquals("mylink", resp.code());
        assertEquals(true, resp.custom());
    }

    @Test
    void createWithConflictingCustomCodeThrows() {
        when(shortLinkRepository.existsByCode("taken")).thenReturn(true);

        CreateLinkRequest req = new CreateLinkRequest("https://example.com", "taken", null);
        assertThrows(CodeConflictException.class,
                () -> service.createShortLink(req, "https://shorten.miku831.fun"));
    }

    @Test
    void createWithTooShortCustomCodeThrows() {
        // 长度 2 < codeMinLength(4)
        CreateLinkRequest req = new CreateLinkRequest("https://example.com", "ab", null);
        assertThrows(IllegalArgumentException.class,
                () -> service.createShortLink(req, "https://shorten.miku831.fun"));
    }

    @Test
    void resolveFromCacheReturnsUrlAndTracks() {
        when(valueOps.get("shortlink:url:abcd")).thenReturn("https://cached.com");

        String url = service.resolveAndTrack("abcd", "1.2.3.4", "UA", null);

        assertEquals("https://cached.com", url);
        // 校验异步埋点被触发
        verify(clickStatService).track(eq("abcd"), eq("1.2.3.4"), eq("UA"), eq(null));
    }

    @Test
    void resolveMissingCodeThrowsNotFound() {
        when(valueOps.get(anyString())).thenReturn(null);
        when(shortLinkRepository.findByCode("nope")).thenReturn(Optional.empty());

        assertThrows(LinkNotFoundException.class,
                () -> service.resolveAndTrack("nope", "ip", "ua", null));
    }

    @Test
    void resolveExpiredCodeThrowsExpired() {
        when(valueOps.get(anyString())).thenReturn(null);
        ShortLink expired = new ShortLink("old", "https://x.com", false,
                LocalDateTime.now().minusDays(1));
        when(shortLinkRepository.findByCode("old")).thenReturn(Optional.of(expired));

        assertThrows(LinkExpiredException.class,
                () -> service.resolveAndTrack("old", "ip", "ua", null));
    }

    @Test
    void getStatsMergesDbAndRedisCounts() {
        ShortLink link = new ShortLink("abc", "https://x.com", false, null);
        link.setClickCount(5L);
        when(shortLinkRepository.findByCode("abc")).thenReturn(Optional.of(link));
        when(clickStatService.pendingClicks("abc")).thenReturn(3L);
        when(accessLogRepository.findByCode(eq("abc"), any(Pageable.class)))
                .thenReturn(Page.<AccessLog>empty());

        LinkStatsResponse stats = service.getStats("abc", 20, "https://shorten.miku831.fun");

        assertEquals(8L, stats.totalClicks());
        assertEquals("abc", stats.code());
        assertFalse(stats.expired());
    }

    @Test
    void getStatsWithInvalidLogLimitThrows() {
        assertThrows(IllegalArgumentException.class,
                () -> service.getStats("abc", 0, "https://shorten.miku831.fun"));
        assertThrows(IllegalArgumentException.class,
                () -> service.getStats("abc", 101, "https://shorten.miku831.fun"));
    }
}
